// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikxsdwjdeafqwxnjgrol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlreHNkd2pkZWFmcXd4bmpncm9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjkyODcsImV4cCI6MjA2NzY0NTI4N30.iq3_pC0XXWy4vbzalKmqNE25W2kYsFLgulbXMagdXQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});